# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/28cb3382-ef08-41c2-b353-15d00b20a549";
      fsType = "ext4";
      options = [ "noatime" "nodiratime" "discard" ]; 
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/fa2067fd-e638-4e14-b80e-17f02b09b883";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0912-15D7";
      fsType = "vfat";
      options = [ "noatime" "nodiratime" "discard" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/778d0805-57e1-4201-bedf-4e70c80c361a"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
}
